### ISSUE TITLE
very slow startup times

### ISSUE THREAD

**Issue by theotheroracle** [commetchat/commet#242] opened 2024-05-23 20:46 UTC
**Describe the bug**
the application takes a full 43 seconds to open

**To Reproduce**
1. have a large matrix account ?? ( dunno, guessing )
1. open the app

**Expected behavior**
app to open can usually be expected to be up to like 5 seconds so this is really not great

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `android`
Version: `v0.2.1`
Git Hash: `cf1a61c2679392dae0a72e91a1c470a472934989`
Detail: `default`

**System Info**

Product: `OnePlus6`
</details>

**Comment by Airyzz** [comment] 2024-05-23 23:44
Could you open the app settings and enable developer mode (Settings > Advanced)? This will measure the performance on the next startup and the information can be accessed in `Settings > Developer Utils > Performance`. Could you please post the information for me

**Comment by theotheroracle** [comment] 2024-05-24 22:01
![ResizedImage_2024-05-24_17-57-20_2368](https://github.com/commetchat/commet/assets/20211219/db8a4d63-5b0e-48a5-829a-b19736c15681)

**Comment by Airyzz** [comment] 2024-05-24 23:06
Thanks, it looks like this is either being caused by something slow in matrix SDK itself, or potentially our custom database implementation - another good experiment could be to test one of our versions pre 0.2, as this did not have our custom database but used the sdks

**Comment by theotheroracle** [comment] 2024-05-24 23:14
sure, i'll try it out

**Comment by theotheroracle** [comment] 2024-05-24 23:25
![Screenshot_20240524-192445_Commet_1](https://github.com/commetchat/commet/assets/20211219/562d379c-a02e-4000-bb5e-38aef7eb7edb)
much better

**Comment by theotheroracle** [comment] 2024-05-25 01:13
after updating the app however, the startup times are still fine ? so maybe it's just something that happens over time, like some cache that never gets cleared

**Comment by theotheroracle** [comment] 2024-05-25 01:14
![Uploading Screenshot_20240524-211308_Commet.png…]()

**Comment by Airyzz** [comment] 2024-05-25 01:31
I suppose as the database starts to contain more stuff performance starts to degrade - keep an eye on it and let me know how it develops 😊

**Comment by theotheroracle** [comment] 2024-05-25 03:22
is there more debugging info I could provide that would help ?

**Comment by Airyzz** [comment] 2024-05-25 03:30
At the moment, I don't think so. I might implement more in depth measuring tools at some point.

In any case, I don't think we'll be moving forward with this database implementation due to a couple other issues I've had with it, so it might not even be worth investigating... I'm working on yet another db implementation right now which may or may not have better performance, hard to say really - I just started it!


I'll keep this open for now, but I think if this new db ends up merged this will probably be closed as not planned. That having been said, if there are similar performance issues in that new implementation, we can absolutely re-open

**Comment by Airyzz** [comment] 2024-05-26 14:39
just an fyi, the pr which contains this new db is #247

**Closed** 2024-06-09 02:52 UTC
