### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by ghost** [commetchat/commet#168] opened 2023-12-03 18:18 UTC
**Describe the bug**

**To Reproduce**
1. Enable developer settings
2. Go to Developer Utils -> Notification -> Message notification
3. Nothing happened

**Expected behavior**
Notification?
**Screenshots**

**Additional context**

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `android`
Version: `v0.1.3`
Git Hash: `c3a2774741664437998902183f2401a069eb58eb`
Detail: `default`

**System Info**

Product: `WP5_EEA`
</details>

**Comment by Airyzz** [comment] 2023-12-03 20:43
Notifications havent yet been implementee for android. See #155 

Closing as duplicate of #68

**Closed as not planned by Airyzz** 2023-12-03 20:43 UTC
