### ISSUE TITLE
libolm has been deprecated and marked insecure

### ISSUE THREAD

**Issue by pluiedev** [commetchat/commet#381] opened 2024-11-01 18:26 UTC
**Describe the bug**
libolm has been [deprecated upstream](https://gitlab.matrix.org/matrix-org/olm#important-libolm-is-now-deprecated) and marked insecure in Nixpkgs, making package managers like Nix refuse to build Commet by default. [vodozemac](https://github.com/matrix-org/vodozemac) should be used instead.

**To Reproduce**
Build this Nix derivation and accompanying lock files: https://gist.github.com/pluiedev/6fea5a1ae2860311763e539509576ae6

**Comment by Airyzz** [comment] 2024-11-01 21:19
Duplicate of #345 - currently waiting for upstream sdk support. Cool to see the ball rolling on a nix package :)

**Closed by Airyzz** 2024-11-01 21:19 UTC

**Comment by pluiedev** [comment] 2024-11-01 21:22
> Cool to see the ball rolling on a nix package :)

It's been *really* tricky since Commet is using Git overrides for media_kit, and pub2nix doesn't support setting the hashes of Git dependencies of Git dependencies, along other issues... I will try to bang my head against it for a bit more and see what I could do
