### ISSUE TITLE
Bubble messages not appearing on Android 11

### ISSUE THREAD

**Issue by everypizza1** [commetchat/commet#240] opened 2024-05-18 13:30 UTC
**Describe the bug**
The app tells the operating system to show bubble messages but they do not appear.

**To Reproduce**
1. Get a notification 
2. Mark as "Priority" conversation in Android 
3. Clear it
4. Get another notification from same person 
5. Bubble does not appear.

**Expected behavior**
Bubbles should appear.

**Screenshots**
Settings page:
![Screenshot_20240518-082902.jpg](https://github.com/commetchat/commet/assets/82726593/0cddab86-c401-4bf9-beb2-33bc287e7b64)
Notifications area:
![Screenshot_20240518-082907.jpg](https://github.com/commetchat/commet/assets/82726593/3aa87749-5670-4f51-afe4-ce188e5aa655)

**Additional context**
My ROM is OxygenOS 11.

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `android`
Version: `v0.2.1`
Git Hash: `cf1a61c2679392dae0a72e91a1c470a472934989`
Detail: `google_services`

**System Info**

Product: `OnePlusN10TMO`
</details>

**Comment by Airyzz** [comment] 2024-05-18 13:39
Do you have any other apps which have bubbles working? I did some quick searching and it does seem like OxygenOS has had some discussion about bubbles not working properly

**Comment by everypizza1** [comment] 2024-05-18 14:09
I currently am not home right now, but when I am, I can check on another device.


________________________________

**Comment by Airyzz** [comment] 2024-05-24 00:08
Closing for now because can't reproduce / not enough information 

Feel free to reopen if you can provide more info

**Closed by Airyzz** 2024-05-24 00:08 UTC

**Comment by everypizza1** [comment] 2024-06-08 20:56
I did just test and it seems to be a problem with the OnePlus. On both of my Samsung devices (one running Android 11, the other running 14), notifications bubble properly.
